development:
  clients:
    default:
      database: money_api_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: money_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        wait_queue_timeout: 15
        max_pool_size: 15
